videos/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'videos'


urlpatterns = [
    #login
    url(r'^$', views.LoginFormView.as_view() , name='login'),
    #logout
    url(r'^logout/$', views.logout , name='logout'),
    #signup page
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    #IndexView
    url(r'^index/$', views.IndexView, name='index'),
    #yuploads
    url(r'^yuploads/$', views.yuploadView, name='yuploads'),
    #uploadView
    url(r'^add/', views.upload, name='add'),
    #delete_object
    url(r'^yuploads/(?P<video_id>(.*?))$', views.delete, name='delete'),
    #search
    url(r'^search/', views.search, name='search'),
]

vidserve/urls.py
from django.conf.urls import include,url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^',include('videos.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.DEFAULT_FILE_STORAGE,document_root=settings.DEFAULT_FILE_STORAGE)

videos/models.py
from django.db import models
from django.contrib.auth.models import User

class Video(models.Model):
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    video_title = models.CharField(max_length=250)
    file_file = models.FileField(default='null')

videos/forms.py
from django.contrib.auth.models import User
from .models import Video
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': 'contatct-form'}))

    class Meta:
        model = User
        fields = ['username','email','password',]

class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username','password',]

class DocumentForm(forms.ModelForm):
    class Meta:
        model = Video
        fields = ('video_title', 'file_file',)

videos/views.py
from django.shortcuts import render,redirect
from django.views import generic
from django.views.generic import View
from django.contrib.auth import authenticate, login
from .forms import UserForm,LoginForm,DocumentForm
from django.contrib.auth.models import User
from django.contrib.auth.views import login
from .models import Video
from django.conf import settings as set
import swiftclient

# Create your views here.

##############login()###########################################################
class LoginFormView(View):
    username=''
    form_class = LoginForm
    template_name = 'registration/login.html'

    def get(self,request):
        if request.session.has_key('username'):
          username = request.session['username']
          return redirect('/index')
        else :
            form = self.form_class(None)
            return render(request, self.template_name, {'form':form,})

    def post(self, request):
        form = self.form_class(request.POST)
        user = authenticate(username=request.POST['username'], password=request.POST['password'])

        if user is not None:
            if user.is_active:
                login(request, user)
                username = user.username
                request.session['username'] = username
                return redirect('videos:index')

        else :
            form.add_error('username', 'credentials are incorrect!')

        return render(request, self.template_name, {'form':form,})

#################registration()#################################################
class UserFormView(View):
    form_class = UserForm
    template_name = 'registration/signup.html'

    def get(self,request):
        if request.session.has_key('username'):
          username = request.session['username']
          return redirect('/index')
        else :
            form = self.form_class(None)
            return render(request, self.template_name, {'form':form,})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid() and form.cleaned_data['password'] == form.cleaned_data['password_confirm']:
            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    request.session['username'] = username
                    return redirect('videos:index')

        else :
            form.add_error('password_confirm', 'The password do not match')

        return render(request, self.template_name, {'form':form,})

###########logout()#############################################################
def logout(request):
    try:
        del request.session['username']
    except:
        pass
    return redirect('/')

###########swiftauth()##########################################################
def swiftauth():
    conn = swiftclient.Connection(set.SWIFT_AUTH_URL,set.SWIFT_USERNAME,set.SWIFT_KEY,auth_version=set.SWIFT_AUTH_VERSION,tenant_name=set.SWIFT_TENANT_NAME)
    return conn
##############index()###########################################################

def IndexView(request):
    if request.session.has_key('username'):
        username = request.session['username']
        x = Video.objects.all()
        conn = swiftauth()
        return render(request,'videos/index.html',{'x':x})
    else:
        return redirect('/')

###############yuploads()#######################################################

def yuploadView(request):
    if request.session.has_key('username'):
        username = request.session['username']
        x = request.user.video_set.all()
        return render(request, 'videos/yupload.html', {"username" : username , 'x':x})
    else:
        return redirect('/')

############upload()############################################################
def upload(request):
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            new = form.save(commit=False)
            new.owner = request.user
            #new.video_title=request.POST["title"]
            #new.file_file=request.FILES["myfile"]
            new.save()
            return redirect('/')
    else:
        form = DocumentForm()
    return render(request, 'videos/upload.html', {
        'form': form
    })

############delete()########################################################
def delete(request,video_id):
    video = Video.objects.get(file_file=video_id)
    conn = swiftauth()
    conn.delete_object(set.SWIFT_CONTAINER_NAME,video_id)
    video.delete()
    return redirect('videos:yuploads')
##########search()#############################################################

def search(request):
    if request.session.has_key('username'):
        username = request.session['username']
        title = str(request.GET["q"])
        x = Video.objects.filter(video_title=title)
        if x:
            return render(request,'videos/index.html',{'x':x})
        else:
            p = "No such videos..."
            return render(request,'videos/index.html',{'p':p,})
    else:
        return redirect('/')

videos/templates/videos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>VidServe</title>
  <!-- Loads path to static files-->
  {% load staticfiles %}
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
  <style>
  .navbar-brand{
    font-family: 'Satisfy', cursive;
  }

  #myInput {
      margin-top: .5%;
      width: 60%;
      border: 1px solid #ddd;
      font-size: 16px;
      border-radius: 10px;
  }
  </style>
</head>

<body>
  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!--Header-->
      <div class="navbar-header">
        <!-- Collapse button (for mobile menu) -->
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- Logo -->
        <a class="navbar-brand" href="/">VidServe</a>
      </div>
      <!--Items-->
      <div class="collapse navbar-collapse" id="topNavBar">
          <!-- User n Video -->
          <ul class="nav navbar-nav">
            {% block active %}
            {% endblock %}
          </ul>
          <!-- Search Form -->
          <form class="navbar-form navbar-left" role="search" method="GET" action="{% url 'videos:search' %}">
            <div class="input-group">
              <input type="text" class="form-control" name="q" value="" placeholder="Search">
              <div class="input-group-btn">
                <button class="btn btn-default" type="submit">
                  <i class="glyphicon glyphicon-search"></i>
                </button>
              </div>
            </div>
          </form>
          <!-- Add n Logout -->
          <ul class="nav navbar-nav navbar-right">
            <li class=""><a href="{% url 'videos:add' %}"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Video</a></li>
            <li class=""><a href="{% url 'videos:logout' %}"><span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout</a></li>
          </ul>

      </div>

    </div>
  </nav>
{% block body %}
{% endblock %}
</body>
</html>

videos/templates/videos/index.html
{% extends 'videos/base.html'%}
{% block active %}
<li class="active"><a href="{% url 'videos:index' %}"><span class="glyphicon glyphicon-film" aria-hidden="true"></span>&nbsp;Videos</a></li>
<li class=""><a href="{% url 'videos:yuploads' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Your Uploads</a></li>
{% endblock %}

{% block body %}

<style>
  .list-group-item{
    display: inline-block;
    padding: 1%;
    margin: 1%;
  }
  video{
    height: 200px;
    width: 300px;
    border: none;
  }
  .container{
    margin-left: 2%;
    margin-right: 2%;
    width: 95%;
  }

</style>

{% if p %}
  <center><h1 style="padding:18%">{{p}}</h1></center>
{% endif %} 
{% if x %}
<div class="container">
<ul class="list-group">
  {% for y in x %}
 <li class="list-group-item">
   <a href="{{y.file_file.url}}">
   <video width="320" height="240" preload="metadata">
   <source src="{{y.file_file.url}}">
  </video>
   <p><h4>{{y.video_title}}</h4></p>
   <p><b><h6>Uploaded by: {{y.owner}}</h6></b></p>
 </a>
</li>
 {% endfor %}
</ul>
</div>
{% endif %}
{% endblock %}

videos/templates/videos/upload.html
{% extends 'videos/base.html'%}
{% block active %}
<li class="active"><a href="{% url 'videos:index' %}"><span class="glyphicon glyphicon-film" aria-hidden="true"></span>&nbsp;Videos</a></li>
<li class=""><a href="{% url 'videos:yuploads' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Your Uploads</a></li>
{% endblock %}

{% block body %}
  <form method="post" style="margin-top: 5%;" enctype="multipart/form-data">
    <div class="container" style="padding-top: 0px;">
      <h1>Upload Video</h1>
      <hr>
    {% csrf_token %}
	<h4>Please upload video in MP4 format.</h4>
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <div class="clearfix">
     <button type="submit" class="signupbtn">submit</button>
   </div>
  </div>
  </form>
{% endblock %}

videos/templates/videos/yupload.html
{% extends 'videos/base.html'%}
{% block active %}
<li class=""><a href="{% url 'videos:index' %}"><span class="glyphicon glyphicon-film" aria-hidden="true"></span>&nbsp;Videos</a></li>
<li class="active"><a activehref="{% url 'videos:yuploads' %}"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Your Uploads</a></li>
{% endblock %}

{% block body %}

<style>
  .list-group-item{
    display: inline-block;
    padding: 1%;
    margin: 1%;
  }
  video{
    height: 200px;
    width: 300px;
    border: none;
  }
  .container{
    margin-left: 2%;
    margin-right: 2%;
    width: 95%;
  }

</style>

{% if x %}
<div class="container">
<ul class="list-group">
  {% for y in x %}
 <li class="list-group-item">
   <a href="{{y.file_file.url}}">
   <video width="320" height="240" preload="metadata">
   <source src="{{y.file_file.url}}">
   </video></a>
   <p><h4>{{y.video_title}}</h4></p>
   <a href="{{y.file_file}}"><button type="button" class="btn btn-outline-primary" style="display: block;margin-right:2%; float:right; background: skyblue;"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span>&nbsp;Remove</button></a>
 </li>
 {% endfor %}
</ul>
</div>
{% endif %}
{% endblock %}